portfolio/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog_id'

urlpatterns = [
    path('personal_blog', views.blog, name='blog'),
    path('<int:id_blog>', views.detail, name='detail')
]

portfolio/personal_portfolio/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('home', views.home, name='home')
]

portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include('personal_portfolio.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    author = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    text = models.TextField()
    email = models.EmailField()
    image = models.ImageField(upload_to='blog/image')
    date = models.DateTimeField()
    description = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.title

portfolio/personal_portfolio/models.py
from django.db import models


# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(max_length=200, blank=True)

    def __str__(self):
        return self.title

portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


# Create your views here.

def blog(request):
    blog = Blog.objects.all()

    return render(request, 'blog/blog.html', {'blogs': blog})


def detail(request, id_blog):
    blog = get_object_or_404(Blog, pk=id_blog)
    return render(request, 'blog/detail_blog.html', {'detail_blog': blog})

portfolio/personal_portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.
def home(request):
    project = Project.objects.all()
    return render(request, 'personal_portfolio/home.html', {'projects': project})

portfolio/blog/templates/blog/blog.html
{% extends 'personal_portfolio/base.html' %}

{% block content %}
    {% for blog in blogs %}
    <hr color="green">
    <a href="{% url 'blog_id:detail' blog.id %}"><h1>Тема: {{ blog.title }}</h1></a>
        <h2>Автор: {{blog.author}}</h2>
        <h2>Фото автора</h2>
        <img src="{{ blog.image.url }}" alt="" width="100" height="100">
        <br>
        {% if blog.email %}
            <h4>Эл. почта: {{blog.email}}</h4>
        {% endif %}
        <h3>Дата создания блога: {{blog.date }}</h3>
    <hr color="yellow">
    <h3>Описание: {{ blog.description }}</h3>

    {% endfor %}
{% endblock %}

portfolio/blog/templates/blog/detail_blog.html
{% extends 'personal_portfolio/base.html' %}

{% block content %}
    <hr color="green">
        <h1>Тема: {{ detail_blog.title }}</h1>
        <h2>Автор: {{detail_blog.author}}</h2>

        <h2>Фото автора</h2>
        <img src="{{ detail_blog.image.url }}" alt="" width="100" height="100">
        <br>
        {% if detail_blog.email %}
            <h4>Эл. почта: {{detail_blog.email}}</h4>
        {% endif %}
        <h3>Дата создания блога: {{detail_blog.date }}</h3>
    <hr color="yellow">
    <h3>Текст</h3>
        <p>{{detail_blog.text}}</p>

{% endblock %}

portfolio/personal_portfolio/templates/personal_portfolio/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'home' %}">Главная</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog_id:blog' %}">Мой блог</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>

    {% block content %} {% endblock %}
     <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

portfolio/personal_portfolio/templates/personal_portfolio/home.html
{% extends 'personal_portfolio/base.html' %}

{% block content %}
    {% for project in projects %}
    <hr color="green">
        <h1>Тема: {{ project.title }}</h1>
    <br>
        <h1>Описание: {{ project.description }}</h1>

    <br>
    <img src="{{ project.image.url }}" alt="" width="100">
    <br>
        {% if project.url %}
            <a href="{{ project.url }}">Ссылка</a>
    <br>
        {% endif %}
    <hr color="yellow">


    {% endfor %}
{% endblock %}